<?php
?>


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Generated by Codia AI</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" />
        <link rel="stylesheet" href="test.css" />
    </head>
    <body>
        <div class="main-container">
            <div class="section">
                <div class="box"><div class="img"></div></div>
                <div class="img-2"></div>
                <div class="pic"></div>
                <div class="img-3"></div>
                <div class="section-2"><div class="img-4"></div></div>
                <div class="group"><div class="img-5"></div></div>
                <div class="img-6"></div>
                <div class="group-2"><div class="img-7"></div></div>
                <div class="Mighty-Button"> <button>HELLO!!!</button></div>
            </div>
            <div class="section-3">
                <div class="wrapper">
                    <span class="text">Hello! Username <br />Welcome Back </span>
                </div>
                <div class="section-4"><span class="text-2">Home Page </span></div>
                <div class="group-3">
                    <div class="box-2"><span class="text-3">Accept Cookies?</span></div>
                </div>
            </div>
            <div class="section-5">
                <div class="group-4"><span class="text-4">Title</span></div>
                <div class="wrapper-2"><span class="text-5">Title</span></div>
                <div class="section-6"><span class="text-6">Title</span></div>
            </div>
            <div class="section-7">
                <div class="img-8"></div>
                <div class="img-9"></div>
                <div class="img-a"></div>
            </div>
            <div class="section-8">
                <div class="box-3">
                    <span class="text-7"
                        >Description:<br />Lorem ipsum dolor sit amet, consectetur
                        adipiscing elit. Sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                        exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat.<br />
                        <br /><br
                    /></span>
                </div>
                <div class="box-4">
                    <span class="text-8"
                        >Description:<br />Lorem ipsum dolor sit amet, consectetur
                        adipiscing elit. Sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                        exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat.<br />
                        <br /><br
                    /></span>
                </div>
                <div class="wrapper-3">
                    <span class="text-9"
                        >Description:<br />Lorem ipsum dolor sit amet, consectetur
                        adipiscing elit. Sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                        exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat.<br />
                        <br /><br
                    /></span>
                </div>
                <div class="section-9"></div>
            </div>
            <div class="box-5">
                <div class="wrapper-4"><span class="text-a">All posts</span></div>
                <div class="section-a"></div>
                <div class="section-b">
                    <div class="wrapper-5">
                        <span class="text-b"
                            >Thanks for visiting my blog website I hope You like it!<br /><br />Click </span
                        ><span class="text-c">Here</span
                        ><span class="text-d"> if you want to give feedback </span>
                    </div>
                </div>
                <div class="box-6">
                    <span class="text-e"
                        >Most liked posts<br />Post 1 - 9 Likes<br />Post 2 - 7 Likes
                        <br />Post 3 - 5 Likes<br />Post 4 - 3 Likes
                    </span>
                </div>
            </div>
        </div>
    </body>
</html>
